server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  ai:
    openai:
      api-key: openAI API Key
      chat:
        options:
          model: tuning model name
#  mvc:
#    view:
#      prefix: /WEB-INF/view/ # JSP ??? ??? ???? ???? ?????.
#      suffix: .jsp
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 100MB
#      max-request-size: 100MB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:career-compass;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10 # ? ?? ???? ?? ??
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

  output:
    ansi:
      enabled: always

logging:
  level:
    '[com.uni.uni_erp]': DEBUG

openAiApi:
  url: https://api.openai.com/v1/chat/completions